FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o notification-worker ./cmd/notification-worker/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/notification-worker .
COPY .env .
# Worker tidak butuh EXPOSE port karena dia hanya mendengarkan RabbitMQ
CMD ["./notification-worker"]
