FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o inventory-service ./cmd/inventory-service/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/inventory-service .
COPY .env .
EXPOSE 50052
CMD ["./inventory-service"]
